services:
  timescaledb:
    image: timescale/timescaledb:2.25.0-pg17
    container_name: timescaledb
    environment:
      POSTGRES_USER: infoclimat
      POSTGRES_PASSWORD: infoclimat2026
      POSTGRES_DB: meteodb
    volumes:
      - timescaledb-data:/var/lib/postgresql/data
      - ./timescaledb-env/meteodb_dump.sql:/docker-entrypoint-initdb.d/dump.sql:ro
    networks:
      - bd_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U infoclimat -d meteodb"]
      interval: 10s
      timeout: 20s
      retries: 10
      start_period: 40s
    restart: unless-stopped

  nginx:
    image: nginx:1.29.5-alpine3.23-perl
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - frontend
      - backend
    networks:
      - app_net

  backend:
    build:
      context: ./backend
    env_file:
      - ./.env
    depends_on:
      timescaledb:
        condition: service_healthy
    networks:
      - app_net
      - bd_net

  frontend:
    build:
      context: ./frontend
    env_file:
      - ./.env
    networks:
      - app_net

  prometheus:
    image: prom/prometheus:v3.3.0
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus-data:/prometheus
    ports:
      - "9090:9090"
    networks:
      - app_net
    restart: unless-stopped

  grafana:
    image: grafana/grafana:11.5.2
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin # Mot de passe par défaut (à changer à la 1ère connexion)
      - GF_SECURITY_ADMIN_PASSWORD=admin # Mot de passe par défaut (à changer à la 1ère connexion)
    volumes:
      - grafana-data:/var/lib/grafana
    networks:
      - app_net
    depends_on:
      - prometheus
    restart: unless-stopped

volumes:
  prometheus-data:
    driver: local
  grafana-data: # Nouveau volume pour sauvegarder vos dashboards
    driver: local
  timescaledb-data:
    driver: local

networks:
  app_net:
  bd_net:


